<header>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Sistema de Cadastro</a>

        <form method="post" action="/EmpSearch" class="form-inline my-2 my-lg-0 mx-auto w-50">
            <input name="empsearch" class="form-control mr-sm-2 w-75" type="search" placeholder="Nome ou e-mail do funcionário" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Procurar</button>
        </form>

    </nav>
</header>



