<div class="container-fluid p-5 mt-5">

    <form class="mx-auto w-50 p-3 bg-dark text-light" method="post" action="/form?id=<?= $this->view->funcionario['id'] ?>" enctype="multipart/form-data"> 

        <div class="form-group">
            <img class="foto img-fluid" width="300" src="./imagens/<?= $this->view->funcionario['id'] ?>/<?= $this->view->funcionario['foto'] ?>">
        </div>

        <div class="form-group">
            <h3 style="display: inline-block;">Nome:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['nome'] ?></h5>
        </div>

        <div class="form-group w-50">
            <h3 style="display: inline-block;">Telefone:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['fone'] ?></h5>
        </div>

        <div class="form-group">
            <h3 style="display: inline-block;">E-mail:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['email'] ?></h5>
        </div>

        <div class="form-group w-50">
            <h3 style="display: inline-block;">CPF:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['cpf'] ?></h5>
        </div>

        <div class="form-group w-50">
            <h3 style="display: inline-block;">RG:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['rg'] ?></h5>
        </div>

        <div class="form-group w-25">
            <h3 style="display: inline-block;">CEP:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['cep'] ?></h5>
        </div>

        <div class="form-group w-25">
            <h3 style="display: inline-block;">UF:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['uf'] ?></h5>
        </div>

        <div class="form-group w-75">
            <h3 style="display: inline-block;">Cidade:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['cidade'] ?></h5>
        </div>

        <div class="form-group">
            <h3 style="display: inline-block;">Endereço:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['endereco'] ?></h5>
        </div>

        <div class="form-group w-75">
            <h3 style="display: inline-block;">Logradouro:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['logradouro'] ?></h5>
        </div>

        <div class="form-group w-25">
            <h3 style="display: inline-block;">Número:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['numero'] ?></h5>
        </div>

        <div class="form-group w-50">
            <h3 style="display: inline-block;">Função:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['funcao'] ?></h5>
        </div>

        <div class="form-group w-25">
            <h3 style="display: inline-block;">Salário:</h3>
            <h5 style="display: inline-block;"><?= $this->view->funcionario['salario'] ?></h5>
        </div>

        <div class="form-group">
            <h3>Observações:</h3>
            <h5><?= $this->view->funcionario['obs'] ?></h5>
        </div>
        
        <div class="form-group mb-0 text-center">
    
            <button type="submit" class="btn btn-outline-light btn-lg w-25">Alterar</button>
            <a href="/funcionario?id=<?= $this->view->funcionario['id'] ?>&action=delete" class="btn btn-outline-light btn-lg w-25">Excluir</a> 
            
        </div>

    </form>
</div>

<!-- Confirmação do cadastro de um novo funcionário -->
<?php if($this->view->action == 'created'){ ?>
    <div class="modal" id="modalInclusao" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-success">CAD SYS</h5>
            </div>
            <div class="modal-body">
                <p>Os dados de <?= $this->view->funcionario['nome'] ?> foram salvos com sucesso!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Concluir</button>
            </div>
        </div>
    </div>
    </div>
    <script>
        $('#modalInclusao').modal('show')
    </script>
<?php } ?>
<!-- Fim confirmação do cadastro de um novo funcionário -->

<!-- Confirmar se o usuário deseja excluir os dados -->
<?php if($this->view->action == 'delete'){ ?>
    <div class="modal" id="modalExclusao" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger">CAD SYS</h5>
            </div>
            <div class="modal-body">
                <p>Deseja realmente EXCLUIR PERMANENTEMENTE os dados de: <?= $this->view->funcionario['nome'] ?></p>
            </div>
            <div class="modal-footer">
                <form action="/delete" method="post">
                    <input type="hidden" name="id" value="<?= $this->view->funcionario['id'] ?>" />
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </form>

                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
    </div>
    <script>
        $('#modalExclusao').modal('show')
    </script>
<?php } ?>
<!-- Fim confirmação se o usuário deseja excluir os dados -->

<!-- Confirmação do cadastro de um novo funcionário -->
<?php if($this->view->action == 'updated'){ ?>
    <div class="modal" id="modalAlteracao" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-warning">CAD SYS</h5>
            </div>
            <div class="modal-body">
                <p>Os dados de <?= $this->view->funcionario['nome'] ?> foram altualizados com sucesso!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Concluir</button>
            </div>
        </div>
    </div>
    </div>
    <script>
        $('#modalAlteracao').modal('show')
    </script>
<?php } ?>
<!-- Fim confirmação do cadastro de um novo funcionário -->