<div class="container w-75 p-5 mt-5 text-center">
	<?php 
				
	if(isset($this->view->funcionarios)){
			
	?>

	<table class="table table-striped">
		<thead class="thead-dark">
			<tr>
				<th scope="col" class="w-25">Código</th>
				<th scope="col" class="w-50">Nome</th>
				<th scope="col" class="w-25">Função</th>
			</tr>
		</thead>
		<tbody>
			
			
			<?php foreach ($this->view->funcionarios as $key => $funcionario) { ?>
			
			<tr>
				<th scope="row"><?= $funcionario['id'] ?></th>
				<td><a href="/funcionario?id=<?= $funcionario['id'] ?>"><?= $funcionario['nome'] ?></a></td>
				<td><?= $funcionario['funcao'] ?></td>
			</tr>

			<?php } ?>
			
		</tbody>
	</table>
</div>

<?php }else{ ?>

	<div class="bg-dark p-5 h-50">
		<h1 class="text-light mt-5">Você ainda não possui funcionários cadastrados.</h1>
		<a href="/form" class="h4">Cadastre já!</a>			
	</div>
<?php } ?>

<!-- Confirmar a exclusão dos dados pelo usuário -->
<?php if($this->view->action == 'deleted'){ ?>
    <div class="modal" id="modalExcluido" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger">CAD SYS</h5>
            </div>
            <div class="modal-body">
                <p>Os dados foram excluídos com sucesso!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
    </div>
    <script>
        $('#modalExcluido').modal('show')
    </script>
<?php } ?>
<!-- Fim confirmação da exclusão dos dados pelo usuário -->