<html>
    <head>
        <meta charset="utf-8" />
        <title>CAD SYS</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </head>
    <body>
    
        <header>
            <nav class="navbar navbar-dark bg-dark ">
                <a class="navbar-brand" href="/">Sistema de Cadastro</a>
                <form method="post" action="/search" class="form-inline my-2 my-lg-0 mx-auto w-75">
                    <a class="btn btn-outline-success my-2 my-sm-0 mr-2" href="form">Novo Funcionário</a>
                    <input name="search" class="form-control w-50" type="search" placeholder="Nome ou e-mail do funcionário" aria-label="Search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Procurar</button>
                </form>
            </nav>
        </header>
        <div class="my-5"></div><!-- Div para ajuste de margem do header e o resto do conteúdo -->
        <?= $this->content() ?>

        
    </body>
</html>